"use strict";

function _typeof(obj) { "@babel/helpers - typeof"; if (typeof Symbol === "function" && typeof Symbol.iterator === "symbol") { _typeof = function _typeof(obj) { return typeof obj; }; } else { _typeof = function _typeof(obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; }; } return _typeof(obj); }

/**
 * CYBS Value Added Service REST API
 * A group of RESTful API that provides value added services to CyberSource clients.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0
 *
 * Do not edit the class manually.
 *
 */
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Vasv2fxratesOrderInformation'], factory);
  } else if ((typeof module === "undefined" ? "undefined" : _typeof(module)) === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Vasv2fxratesOrderInformation'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }

    root.CyberSource.ForeignExchangeRatesRequest = factory(root.CyberSource.ApiClient, root.CyberSource.Vasv2fxratesOrderInformation);
  }
})(void 0, function (ApiClient, Vasv2fxratesOrderInformation) {
  'use strict';
  /**
   * The ForeignExchangeRatesRequest model module.
   * @module model/ForeignExchangeRatesRequest
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>ForeignExchangeRatesRequest</code>.
   * @alias module:model/ForeignExchangeRatesRequest
   * @class
   */

  var exports = function exports() {
    var _this = this;
  };
  /**
   * Constructs a <code>ForeignExchangeRatesRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ForeignExchangeRatesRequest} obj Optional instance to populate.
   * @return {module:model/ForeignExchangeRatesRequest} The populated <code>ForeignExchangeRatesRequest</code> instance.
   */


  exports.constructFromObject = function (data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('orderInformation')) {
        obj['orderInformation'] = Vasv2fxratesOrderInformation.constructFromObject(data['orderInformation']);
      }
    }

    return obj;
  };
  /**
   * @member {module:model/Vasv2fxratesOrderInformation} orderInformation
   */


  exports.prototype['orderInformation'] = undefined;
  return exports;
});