"use strict";

function _typeof(obj) { "@babel/helpers - typeof"; if (typeof Symbol === "function" && typeof Symbol.iterator === "symbol") { _typeof = function _typeof(obj) { return typeof obj; }; } else { _typeof = function _typeof(obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; }; } return _typeof(obj); }

/**
 * CYBS Value Added Service REST API
 * A group of RESTful API that provides value added services to CyberSource clients.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0
 *
 * Do not edit the class manually.
 *
 */
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if ((typeof module === "undefined" ? "undefined" : _typeof(module)) === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }

    root.CyberSource.Vasv2accountnumberlookuppost201responsePaymentAccountInformationFeaturesBrands = factory(root.CyberSource.ApiClient);
  }
})(void 0, function (ApiClient) {
  'use strict';
  /**
   * The Vasv2accountnumberlookuppost201responsePaymentAccountInformationFeaturesBrands model module.
   * @module model/Vasv2accountnumberlookuppost201responsePaymentAccountInformationFeaturesBrands
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>Vasv2accountnumberlookuppost201responsePaymentAccountInformationFeaturesBrands</code>.
   * @alias module:model/Vasv2accountnumberlookuppost201responsePaymentAccountInformationFeaturesBrands
   * @class
   */

  var exports = function exports() {
    var _this = this;
  };
  /**
   * Constructs a <code>Vasv2accountnumberlookuppost201responsePaymentAccountInformationFeaturesBrands</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Vasv2accountnumberlookuppost201responsePaymentAccountInformationFeaturesBrands} obj Optional instance to populate.
   * @return {module:model/Vasv2accountnumberlookuppost201responsePaymentAccountInformationFeaturesBrands} The populated <code>Vasv2accountnumberlookuppost201responsePaymentAccountInformationFeaturesBrands</code> instance.
   */


  exports.constructFromObject = function (data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }

      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
    }

    return obj;
  };
  /**
   * For co-badged credit cards, the sequentially numbered names of the credit card brands. For example, for a co-badged credit card payment, you might see the following reply: \"brands\":[{\"name\":\"Visa\",\"type\":\"001\"}, {\"name\":\"Carte Bancaire\",\"type\":\"036\"}]  Note A co-badged card is not the same as a coâ€‘branded card: - A co-badged card includes two or more card types, such as Visa and Carte Bancaire. - A co-branded card is sponsored by an issuing bank and a retail merchant. See http://apps.cybersource.com/library/documentation/BIN_Lookup/BIN_Lookup_SO_API/BIN_Lookup_SO_API.pdf Example 5, and Example 10. 
   * @member {String} name
   */


  exports.prototype['name'] = undefined;
  /**
   * For co-badged credit cards, the sequentially numbered type codes of the credit card brands. For example, for a co-badged credit card payment, you might see the following reply: \"brands\":[{\"name\":\"Visa\",\"type\":\"001\"}, {\"name\":\"Carte Bancaire\",\"type\":\"036\"}]  Note A co-badged card is not the same as a coâ€‘branded card: - A co-badged card includes two or more card types, such as Visa and Carte Bancaire. - A co-branded card is sponsored by an issuing bank and a retail merchant. See See http://apps.cybersource.com/library/documentation/BIN_Lookup/BIN_Lookup_SO_API/BIN_Lookup_SO_API.pdf Example 5, and Example 10. 
   * @member {String} type
   */

  exports.prototype['type'] = undefined;
  return exports;
});