"use strict";

function _typeof(obj) { "@babel/helpers - typeof"; if (typeof Symbol === "function" && typeof Symbol.iterator === "symbol") { _typeof = function _typeof(obj) { return typeof obj; }; } else { _typeof = function _typeof(obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; }; } return _typeof(obj); }

/**
 * CYBS Value Added Service REST API
 * A group of RESTful API that provides value added services to CyberSource clients.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0
 *
 * Do not edit the class manually.
 *
 */
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if ((typeof module === "undefined" ? "undefined" : _typeof(module)) === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }

    root.CyberSource.VasV2PaymentsPost201ResponseLinksVoid = factory(root.CyberSource.ApiClient);
  }
})(void 0, function (ApiClient) {
  'use strict';
  /**
   * The VasV2PaymentsPost201ResponseLinksVoid model module.
   * @module model/VasV2PaymentsPost201ResponseLinksVoid
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>VasV2PaymentsPost201ResponseLinksVoid</code>.
   * @alias module:model/VasV2PaymentsPost201ResponseLinksVoid
   * @class
   */

  var exports = function exports() {
    var _this = this;
  };
  /**
   * Constructs a <code>VasV2PaymentsPost201ResponseLinksVoid</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VasV2PaymentsPost201ResponseLinksVoid} obj Optional instance to populate.
   * @return {module:model/VasV2PaymentsPost201ResponseLinksVoid} The populated <code>VasV2PaymentsPost201ResponseLinksVoid</code> instance.
   */


  exports.constructFromObject = function (data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('href')) {
        obj['href'] = ApiClient.convertToType(data['href'], 'String');
      }

      if (data.hasOwnProperty('method')) {
        obj['method'] = ApiClient.convertToType(data['method'], 'String');
      }
    }

    return obj;
  };
  /**
   * This is the endpoint of the resource that was created by the successful request.
   * @member {String} href
   */


  exports.prototype['href'] = undefined;
  /**
   * `method` refers to the HTTP method that you can send to the `self` endpoint to retrieve details of the resource.
   * @member {String} method
   */

  exports.prototype['method'] = undefined;
  return exports;
});