"use strict";

function _typeof(obj) { "@babel/helpers - typeof"; if (typeof Symbol === "function" && typeof Symbol.iterator === "symbol") { _typeof = function _typeof(obj) { return typeof obj; }; } else { _typeof = function _typeof(obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; }; } return _typeof(obj); }

/**
 * CYBS Value Added Service REST API
 * A group of RESTful API that provides value added services to CyberSource clients.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0
 *
 * Do not edit the class manually.
 *
 */
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if ((typeof module === "undefined" ? "undefined" : _typeof(module)) === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CyberSource) {
      root.CyberSource = {};
    }

    root.CyberSource.Vasv2accountnumberlookuppost201responsePaymentAccountInformationFeaturesNetwork = factory(root.CyberSource.ApiClient);
  }
})(void 0, function (ApiClient) {
  'use strict';
  /**
   * The Vasv2accountnumberlookuppost201responsePaymentAccountInformationFeaturesNetwork model module.
   * @module model/Vasv2accountnumberlookuppost201responsePaymentAccountInformationFeaturesNetwork
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>Vasv2accountnumberlookuppost201responsePaymentAccountInformationFeaturesNetwork</code>.
   * @alias module:model/Vasv2accountnumberlookuppost201responsePaymentAccountInformationFeaturesNetwork
   * @class
   */

  var exports = function exports() {
    var _this = this;
  };
  /**
   * Constructs a <code>Vasv2accountnumberlookuppost201responsePaymentAccountInformationFeaturesNetwork</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Vasv2accountnumberlookuppost201responsePaymentAccountInformationFeaturesNetwork} obj Optional instance to populate.
   * @return {module:model/Vasv2accountnumberlookuppost201responsePaymentAccountInformationFeaturesNetwork} The populated <code>Vasv2accountnumberlookuppost201responsePaymentAccountInformationFeaturesNetwork</code> instance.
   */


  exports.constructFromObject = function (data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }

      if (data.hasOwnProperty('networkRoutingOrder')) {
        obj['networkRoutingOrder'] = ApiClient.convertToType(data['networkRoutingOrder'], 'String');
      }

      if (data.hasOwnProperty('pushFundsDomesticIndicator')) {
        obj['pushFundsDomesticIndicator'] = ApiClient.convertToType(data['pushFundsDomesticIndicator'], 'String');
      }

      if (data.hasOwnProperty('pushFundsCrossBorderIndicator')) {
        obj['pushFundsCrossBorderIndicator'] = ApiClient.convertToType(data['pushFundsCrossBorderIndicator'], 'String');
      }

      if (data.hasOwnProperty('pullFundsDomesticIndicator')) {
        obj['pullFundsDomesticIndicator'] = ApiClient.convertToType(data['pullFundsDomesticIndicator'], 'String');
      }

      if (data.hasOwnProperty('pullFundsCrossBorderIndicator')) {
        obj['pullFundsCrossBorderIndicator'] = ApiClient.convertToType(data['pullFundsCrossBorderIndicator'], 'String');
      }
    }

    return obj;
  };
  /**
   * Network identifier for the related elements in the array.  This field can be returned for mode A and mode P. For details, see the `network_id` field description in [BIN Lookup Service Using the SCMP API.] (http://apps.cybersource.com/library/documentation/BIN_Lookup/BIN_Lookup_SCMP_API/html/) 
   * @member {String} id
   */


  exports.prototype['id'] = undefined;
  /**
   * One or more codes that indicate which networks are supported for the card.  For details, see the `network_order` field description in [BIN Lookup Service Using the SCMP API.](http://apps.cybersource.com/library/documentation/BIN_Lookup/BIN_Lookup_SCMP_API/html/) This field can be returned for mode A and mode P. 
   * @member {String} networkRoutingOrder
   */

  exports.prototype['networkRoutingOrder'] = undefined;
  /**
   * Indicates whether domestic OCT transactions are supported on network specified by the network ID value. Domestic means that the issuer and acquirer are in the same country.  Possible values: - true: Supported - false: Not supported - Data not available: if BIN files do not have this card's information  This field is returned only for debit networks that are supported for the card number submitted in the request.  This field can be returned for mode A and mode P. 
   * @member {String} pushFundsDomesticIndicator
   */

  exports.prototype['pushFundsDomesticIndicator'] = undefined;
  /**
   * Indicates whether cross-border OCT transactions are supported on network specified by the network ID value. Cross border means that the issuer and acquirer are in different countries.  Possible values: - true: Supported - false: Not supported - Data not available: if BIN files do not have this card's information  This field is returned only for debit networks that are supported for the card number submitted in the request.  This field can be returned for mode A and mode P. 
   * @member {String} pushFundsCrossBorderIndicator
   */

  exports.prototype['pushFundsCrossBorderIndicator'] = undefined;
  /**
   * Indicates whether domestic AFT transactions are supported on network specified by the network ID value. Domestic means that the issuer and acquirer are in the same country.  Possible values: - true: Supported - false: Not supported - Data not available: if BIN files do not have this card's information  This field is returned only for debit networks that are supported for the card number submitted in the request.  This field can be returned for mode A and mode P. 
   * @member {String} pullFundsDomesticIndicator
   */

  exports.prototype['pullFundsDomesticIndicator'] = undefined;
  /**
   * Indicates whether cross-border AFT transactions are supported on network specified by the network ID value. Cross border means that the issuer and acquirer are in different countries.  Possible values: - true: Supported - false: Not supported - Data not available: if BIN files do not have this card's information  This field is returned only for debit networks that are supported for the card number submitted in the request.  This field can be returned for mode A and mode P. 
   * @member {String} pullFundsCrossBorderIndicator
   */

  exports.prototype['pullFundsCrossBorderIndicator'] = undefined;
  return exports;
});